/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * BUCKET Admin API
 * BUCKET Admin 시스템 API 문서
 * OpenAPI spec version: 1.0.0
 */

export interface DriverPickupItem {
  id?: string;
  customerName?: string;
  customerPhone?: string;
  address?: string;
  collectionDate?: string;
  timeSlot?: string;
  status?: string;
  statusBadgeClass?: string;
  collectedWeight?: number;
  completedAt?: string;
  createdAt?: string;
}
