/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * BUCKET Admin API
 * BUCKET Admin 시스템 API 문서
 * OpenAPI spec version: 1.0.0
 */

export interface DriverPickupDetail {
  id?: string;
  customerName?: string;
  customerPhone?: string;
  customerEmail?: string;
  address?: string;
  zipCode?: string;
  roadAddress?: string;
  detailAddress?: string;
  buildingName?: string;
  collectionDate?: string;
  timeSlot?: string;
  specificTime?: string;
  status?: string;
  statusBadgeClass?: string;
  description?: string;
  customerNotes?: string;
  accessNotes?: string;
  entrancePassword?: string;
  collectedWeight?: number;
  photoUrls?: string[];
  completedAt?: string;
  createdAt?: string;
  expectedFee?: number;
  baseAllowance?: number;
  incentiveAmount?: number;
}
