/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * BUCKET Admin API
 * BUCKET Admin 시스템 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { IncentiveDetail } from './incentiveDetail';

export interface DriverFeeEstimate {
  pickupId?: string;
  collectionDate?: string;
  collectedWeight?: number;
  baseAllowance?: number;
  perKgAllowance?: number;
  weightBasedFee?: number;
  incentiveAmount?: number;
  incentiveDetails?: IncentiveDetail[];
  totalFee?: number;
}
