/**
 * Generated by orval v8.0.0-rc.3 🍺
 * Do not edit manually.
 * BUCKET Admin API
 * BUCKET Admin 시스템 API 문서
 * OpenAPI spec version: 1.0.0
 */

export interface IncentiveDetail {
  policyName?: string;
  policyType?: string;
  rewardAmount?: number;
  description?: string;
}
